version: '3'
services:
  php:
    build: docker/php
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/var/www/html
     - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
     - ./docker/apache:/etc/apache2/sites-enabled:ro
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  node:
    build: docker/node
    command: node dev-server.js
    working_dir: /usr/src/app
    volumes:
     - .:/usr/src/app
    ports:
     - "81:81"
    networks:
     - appnet
  db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: project-name
      POSTGRES_DB: project-name
      POSTGRES_USER: project-name
    volumes:
     - data:/var/lib/postgresql/data
    networks:
     - appnet
  mail:
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
     - appnet
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: 12345678
    volumes:
      - s3:/data
    networks:
     - appnet
    command: server /data
    # See README.md
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
  s3:
    driver: "local"
